"""Generate an Onshape FeatureScript for a designed gear train.

The generated Feature Studio embeds the tooth profiles (from solid_model) as point
arrays and reuses the geometry builder of onshape/cycloidalPlanetary.fs, so the
feature offers thickness, tooth type, helix angle, layout and stage gap as live
parameters inside Onshape.  Works for every gear type the tool can export,
including the cycloidal ones whose profiles are not closed-form.

Usage:
    code = generate_featurescript(model, title='Compound planetary 22/7/8 + 21/6/9')
    open('gearTrain.fs', 'w').write(code)
Paste into a Feature Studio, then add the feature in a Part Studio.
"""
import os
import re
from typing import Dict, List, Sequence

import numpy as np

FS_VERSION = '1948'
MAX_POINTS_PER_LOOP = 800
BUILDER_FILE = os.path.join(os.path.dirname(__file__), 'onshape', 'cycloidalPlanetary.fs')


def builder_source() -> str:
    """The shared builder section of cycloidalPlanetary.fs (enums, bounds, geometry functions)."""
    src = open(BUILDER_FILE, encoding='utf-8').read()
    m = re.search(r'// ---- builder begin -+\n(.*?)// ---- builder end -+\n', src, re.S)
    if not m:
        raise RuntimeError('builder markers not found in cycloidalPlanetary.fs')
    return m.group(1)


def _downsample(loop: Sequence, limit: int = MAX_POINTS_PER_LOOP) -> np.ndarray:
    pts = np.asarray(loop, dtype=float)
    if len(pts) <= limit:
        return pts
    stride = int(np.ceil(len(pts) / limit))
    return pts[::stride]


def _fmt_loop(loop: Sequence) -> str:
    pts = _downsample(loop)
    return '[' + ', '.join(f'[{x:.5f}, {y:.5f}]' for x, y in pts) + ']'


def _fs_identifier(name: str) -> str:
    ident = re.sub(r'[^A-Za-z0-9_]', '_', name)
    return ident if re.match(r'[A-Za-z_]', ident) else '_' + ident


def generate_featurescript(model: Dict, title: str = 'Gear train', feature_name: str = 'verrosGearTrain') -> str:
    """model: the dict from solid_model.build_solid_model (parts need 'hand' and 'ref_radius_mm')."""
    parts: List[Dict] = model['parts']
    if not parts:
        raise ValueError('The solid model has no parts.')
    lines = []
    lines.append(f'FeatureScript {FS_VERSION};')
    lines.append(f'import(path : "onshape/std/geometry.fs", version : "{FS_VERSION}.0");')
    lines.append('')
    lines.append('/*')
    lines.append(f' * {title}')
    lines.append(' * Generated by the verros gear train designer (pygeartrain).')
    lines.append(f" * Profiles are in mm at the export scale (scale factor {model.get('scale_factor', 1.0):.6f});")
    lines.append(' * thickness, tooth type, helix angle, layout and stage gap are live feature parameters.')
    lines.append(' * Paste into a Feature Studio, then add the feature to a Part Studio.')
    lines.append(' */')
    lines.append('')
    # embedded profile data, one constant per part
    for part in parts:
        ident = _fs_identifier(part['name']).upper()
        faces = []
        for face in part['faces']:
            holes = ', '.join(_fmt_loop(h) for h in face['holes'])
            if part.get('internal') and part.get('outer_radius_mm'):
                # ring gear wall: a true circle instead of the polygonised one
                outer = '{ "circle" : %.6f }' % float(part['outer_radius_mm'])
            else:
                outer = _fmt_loop(face['outer'])
            faces.append('{ "outer" : ' + outer + ', "holes" : [' + holes + '] }')
        lines.append(f'const FACES_{ident} = [' + ', '.join(faces) + '];')
    lines.append('')
    lines.append('const PARTS = [')
    for part in parts:
        ident = _fs_identifier(part['name']).upper()
        lines.append('    { "name" : "%s", "faces" : FACES_%s, "internal" : %s, "fuse" : %s, "refRadius" : %.6f, "hand" : %d },' % (
            part['name'], ident, 'true' if part.get('internal') else 'false', 'true' if part.get('fuse') else 'false',
            float(part.get('ref_radius_mm', 0.0)), int(part.get('hand', 0))))
    lines.append('];')
    lines.append('')
    lines.append('const INSTANCES = [')
    for inst in model.get('instances', []):
        lines.append('    { "part" : "%s", "angle" : %.9f, "x" : %.6f, "y" : %.6f, "layer" : %d },' % (
            inst['part'], float(np.radians(inst['angle_deg'])), float(inst['x_mm']), float(inst['y_mm']), int(inst['layer'])))
    lines.append('];')
    lines.append('')
    tooth_default = {'spur': 'SPUR', 'helix': 'HELIX', 'herringbone': 'HERRINGBONE'}.get(model.get('gear_type', 'spur'), 'SPUR')
    lines.append('annotation { "Feature Type Name" : "%s", "Feature Type Description" : "Gear train generated by the verros designer" }' % title.replace('"', ''))
    lines.append(f'export const {feature_name} = defineFeature(function(context is Context, id is Id, definition is map)')
    lines.append('    precondition')
    lines.append('    {')
    lines.append('        annotation { "Name" : "Face width (thickness)" }')
    lines.append('        isLength(definition.thickness, THICKNESS_BOUNDS);')
    lines.append('        annotation { "Name" : "Tooth type", "Default" : "%s" }' % tooth_default)
    lines.append('        definition.toothType is ToothType;')
    lines.append('        if (definition.toothType != ToothType.SPUR)')
    lines.append('        {')
    lines.append('            annotation { "Name" : "Helix angle" }')
    lines.append('            isAngle(definition.helixAngle, HELIX_BOUNDS);')
    lines.append('        }')
    lines.append('        annotation { "Name" : "Tooth clearance (total backlash)" }')
    lines.append('        isLength(definition.clearance, BACKLASH_BOUNDS);')
    lines.append('        annotation { "Name" : "Gap between stacked stages" }')
    lines.append('        isLength(definition.layerGap, GAP_BOUNDS);')
    lines.append('        annotation { "Name" : "Layout" }')
    lines.append('        definition.layout is Layout;')
    lines.append('        annotation { "Name" : "Smooth splines (off = polylines)", "Default" : true }')
    lines.append('        definition.smooth is boolean;')
    lines.append('    }')
    lines.append('    {')
    lines.append('        buildGearTrain(context, id, { "parts" : PARTS, "instances" : INSTANCES }, {')
    lines.append('            "thickness" : definition.thickness,')
    lines.append('            "layerGap" : definition.layerGap,')
    lines.append('            "toothType" : definition.toothType,')
    lines.append('            "helixAngle" : definition.toothType == ToothType.SPUR ? 0 * degree : definition.helixAngle,')
    lines.append('            "layout" : definition.layout,')
    lines.append('            "clearance" : definition.clearance,')
    lines.append('            "smooth" : definition.smooth')
    lines.append('        });')
    lines.append('    });')
    lines.append('')
    lines.append(builder_source().rstrip('\n'))
    lines.append('')
    return '\n'.join(lines)
